name: Checkout

on: 
  [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: build_oure_jest_test
      run: |
        npm install
        npm run test 

