name: Checkout

on: 
  [push]

jobs:
  build:
    strategy: 
      matrix: 
        os: [windows-latest, ubuntu-latest, macos-latest]
        checkout: [Funktioniert_1, Funktioniert_2]
    runs-on: ${{ matrix.os }}

    steps:
    - name: checkout
      uses: actions/checkout@v2
      run : |
        echo ${{ matrix.checkout}}
