name: Checkout

on: 
  [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: build_oure_jest_test
      run: |
        npm install
        npm run test 
  
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build image
        run: docker image build -t muazar/cicd-demo .

      - name: Push image
        run: docker push muazar/cicd-demo:latest
  
  bring_live:
    runs-on: aws_ec2

    steps:
      - name: fetchb image
        run: docker pull muazar/cicd-demo:latest

      - name: run image
        run: docker container rm -f server

      - name: run new container 
        run: docker container run -d -p 3000:3000 --name server muaz-ar/greetingapp:latest 