name: Checkout

on:
  [push]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Build and test
        run: |
          npm install
          npm test
  
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build image
        run: docker image build -t muazar/cicd-demo .

      - name: Push image
        run: docker push muazar/cicd-demo:latest
        
 
