name: Checkout

on: 
  [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: build_oure_jest_test
      run: |
        npm install
        npm run test 
  
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build image
        run: docker image build -t muaz-ar/cicd-demo .

      - name: Push image
        run: docker push muaz-ar/cicd-demo:latest
  
 